#!/bin/sh -e
#
# test for kuten bug
#
# $Id: kakasi-7,v 1.3 2013-12-17 04:49:58 knok Exp $

LOG=`pwd`/test-log
echo '  *** disabled ' $0 >> $LOG
exit 0
echo '  *** starting ' $0 >> $LOG

. ./env.sh

GNUECHO=/bin/echo

# a SPECIAL character KUTEN
out=`$GNUECHO -e '\241\242' | ../src/kakasi -ieuc -oeuc -w`
cmp=`$GNUECHO -e '\241\242'`

if [ ! "x$out" == "x$cmp" ]
then
      echo "failed." >> $LOG
      echo "output: $out" >> $LOG
      echo "expection: $cmp" >> $LOG
      exit 1
fi

exit 0
